Map<String, String> english = {
  'WELCOME_BACK': 'Selamat Datang Kembali',
  'HOME': 'Beranda',
  'HISTORY': 'Riwayat',
  'PROFILE': 'Profil',
  'COMPLETE_DELIVERY': 'Selesaikan Pengiriman',
  'RETURN_DELIVERY': 'Pengiriman Kembali',
  'ACTIVE_ORDERS': 'Pesanan Aktif',
  'SEE_DETAILS': 'Lihat Detail',
  'GET_DIRECTION': 'Dapatkan Petunjuk',
  'ORDER_ID': 'ID Pesanan : ',
  'SEE_ORDER_DETAILS': 'Lihat Detail Pesanan',
  'CONFIRM_DELIVERY': 'Konfirmasi Pengiriman',
  'CUSTOMER': 'Pelanggan',
  'ORDER_DETAILS': 'Detail Pesanan',
  'YOUR_ESTIMATE_DELIVERY_TIME': 'Perkiraan waktu pengiriman Anda',
  'PAYMENT_INFO': 'Informasi Pembayaran',
  'METHOD': 'Metode',
  'STATUS': 'Status',
  'ORDER_SUMMERY': 'Ringkasan Pesanan',
  'EXTRAS': 'Ekstra',
  'INSTRUCTIONS': 'Instruksi: ',
  'SUBTOTAL': 'Subtotal',
  'DISCOUNT': 'Diskon',
  'DELIVERY_CHARGE': 'Biaya Pengiriman',
  'TOTAL': 'Total',
  'CONFIRM_DELIVERY_ALERT': 'Apakah Anda yakin ingin mengonfirmasi pengiriman?',
  'NO_CANCEL': 'Tidak, Batal',
  'YES_CONFIRM': 'Ya, Konfirmasi',
  'YES_COLLECT': 'Ya, Ambil',
  'CASH_ON_DELIVERY': 'Bayar Tunai',
  'ORDER_SUCCESSFULLY_DELIVERED': 'Pesanan Berhasil Dikirim',
  'BACK_TO_HOME': 'Kembali ke Beranda',
  'OPEN': 'Buka',
  'MY_PROFILE': 'Profil Saya',
  'BRANCH': 'Cabang',
  'LOG_OUT': 'Keluar',
  'ERROR': 'Kesalahan',
  'SUCCESS': 'Berhasil',
  'CHANGE_PASSWORD': 'Ubah Kata Sandi',
  'CHANGE_LANGUAGE': 'Ubah Bahasa',
  'TERMS_CONDITION': 'Syarat & Ketentuan',
  'PRIVACY_POLICY': 'Kebijakan Privasi',
  'EDIT_PROFILE': 'Edit Profil',
  'FIRST_NAME': 'Nama Depan',
  'LAST_NAME': 'Nama Belakang',
  'EMAIL': 'Email',
  'PASSWORD': 'Kata Sandi',
  'MOBILE_NUMBER': 'Nomor Telepon',
  'UPDATE_PROFILE': 'Perbarui Profil',
  'OLD_PASSWORD': 'Kata Sandi Lama',
  'NEW_PASSWORD': 'Kata Sandi Baru',
  'RETYPE_NEW_PASSWORD': 'Ketik Ulang Kata Sandi Baru',
  'DELETE_ACCOUNT': 'Hapus Akun',
  'PROFILE_UPDATE': 'Profil Diperbarui',
  'PROFILE_UPDATE_SUCCESSFULLY': 'Profil Diperbarui dengan Sukses',
  'PASSWORD_UPDATE_SUCCESSFULLY': 'Kata Sandi Diperbarui dengan Sukses',
  'CONFIRM_NEW_PASSWORD': 'Konfirmasi Kata Sandi Baru',
  'PLEASE_ENTER_VALID_INPUT': 'Harap masukkan input yang valid',
  'PRESS_BACK_AGAIN_TO_EXIT': 'Tekan kembali lagi untuk keluar.',
  'REMEMBER_ME': 'Ingat Saya',
  'ORDER_HISTORY': 'Riwayat Pesanan',
  "IMAGE_SHOULD_BE_LESS_THAN_2MB": 'Ukuran gambar harus kurang dari 2MB',
  "PROFILE_IMAGE_SAVED_SUCCESSFULLY": 'Gambar profil berhasil disimpan',
  'SOMETHING_WRONG': 'Ada Kesalahan',
  "YOU_HAVE_NO_ORDER_FOR_DELIVERY":
      "Anda tidak memiliki pesanan untuk pengiriman",
  "WAIT_NOTE":
      "Tunggu sampai manajer cabang mengirimkan pesanan kepada Anda untuk pengiriman.",
  "YOU_HAVE_NO_ORDER_HISTORY": "Anda tidak memiliki riwayat pesanan",
  "ALL_BRANCH": "Semua Cabang",
  "INSTRUCTION": "Instruksi",
  "DELIVERY_ADDRESS": "Alamat Pengiriman",
  "PAID": "Dibayar",
  "UNPAID": "Belum Dibayar",
  "PICK_PAY": "Pilih & Bayar",
  "DO_YOU_COLLECT_PAYMENT": "Apakah Anda Mengambil Pembayaran?",
  "AMOUNT": "Jumlah",
  "PLEASE_TYPE_FIRST_NAME": "Harap ketik nama depan Anda",
  "PLEASE_TYPE_LAST_NAME": "Harap ketik nama belakang Anda",
  "PLEASE_TYPE_EMAIL": "Harap ketik email Anda",
  "PLEASE_TYPE_OLD_PASSWORD": "Harap ketik kata sandi lama Anda",
  "PLEASE_TYPE_NEW_PASSWORD": "Harap ketik kata sandi baru Anda",
  "PLEASE_RETYPE_PASSWORD": "Harap ketik ulang kata sandi",
  "PASSWORD_MUST_BE_SIX": "Kata sandi harus minimal 6 karakter",
  "ENTER_VALID_EMAIL": "Masukkan email yang valid",
  "PLEASE_TYPE_PASSWORD": "Harap ketik kata sandi",
  "LOCATION_SERVICE_DENIED": "Layanan lokasi ditolak!",
  "LOCATION_PERMISSION_NOT_ENABLED": "Izin lokasi tidak diaktifkan!",
};
